kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    component: elasticsearch
  name: storage-elasticsearch-1
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-es-1
