apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-1
  namespace: logging
spec:
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    kind: PersistentVolumeClaim
    name: storage-elasticsearch-1
    namespace: logging
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # FIXME: use the right IP
    server: 10.0.0.1
    path: "/mnt/es-1"
