apiVersion: v1
data:
  config.toml: |
    concurrent = 4
    check_interval = 0

    [[runners]]
      name = "Kubernetes Runner"
      url = "http://git.lab.int/ci"
      token = "158c409d441580d3e5c1846f90aa00"
      executor = "kubernetes"
      [runners.cache]
      [runners.kubernetes]
        namespace = "gitlab"
        privileged = true
        cpus = "1"
        memory = "2Gi"
        service_cpus = "1"
        service_memory = "2Gi"
        helper_cpus = "500m"
        helper_memory = "512Mi"
kind: ConfigMap
metadata:
  name: gitlab-runner
  namespace: gitlab

